#!/bin/bash
# myapp daemon
# chkconfig: 345 20 80
# description: tnrs services daemon
# processname: tnrs-services

DAEMON_PATH="/opt/tnrs-services"

DAEMON="services_start.sh"
DAEMONOPTS=""

NAME=tnrs-services
DESC="tnrs services services"
PIDFILE=/var/run/tnrs/$NAME.pid
LOGFILE=/var/log/httpd/$NAME.log
SCRIPTNAME=/etc/init.d/$NAME
USER='tnrs'

case "$1" in
start)
	printf "%-50s" "Starting $NAME..."
	cd $DAEMON_PATH
	su tnrs -c "sh $DAEMON $DAEMONOPTS & echo \$! &>$PIDFILE" &> "$LOGFILE"
#PID=$(su $USER -c "sh $DAEMON $DAEMONOPTS > /dev/null 2>&1 & exit $!")
        if [ ! -f $PIDFIDFILE ]; then
            printf "%s\n" "Fail"
        else
            printf "%s\n" "Ok"
        fi
;;
status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping $NAME"
            PID=`cat $PIDFILE`
            cd $DAEMON_PATH
        if [ -f $PIDFILE ]; then
            pkill -TERM -P $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;

restart)
  	$0 stop
  	$0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
