CREATE TABLE `famlist` (
  `FAMILY_ID` int(11) unsigned NOT NULL,
  `FAMILY` VARCHAR(50) DEFAULT NULL,
  `AUTHORITY` VARCHAR(150) DEFAULT NULL,
  `FAM_LENGTH` int(2) DEFAULT NULL,
  `NEAR_MATCH_FAMILY` VARCHAR(50) DEFAULT NULL,
  `SEARCH_FAMILY_NAME` VARCHAR(50) DEFAULT NULL,
  `sgn_head1` char(1) DEFAULT NULL,
  `sgn_head2` char(2) DEFAULT NULL,
  `sgn_head3` char(3) DEFAULT NULL,
  PRIMARY KEY (`FAMILY_ID`),
  KEY `famlist_FAMILY_NDX`(`FAMILY`),
  KEY `famlist_AUTHORITY_NDX`(`AUTHORITY`),
  KEY `famlist_FAM_LENGTH_NDX`(`FAM_LENGTH`),
  KEY `famlist_NEAR_MATCH_FAMILY_NDX`(`NEAR_MATCH_FAMILY`),
  KEY `famlist_SEARCH_FAMILY_NAME`(`SEARCH_FAMILY_NAME`),
  KEY `famlist_SGN_HEAD1_NDX` (`sgn_head1`),
  KEY `famlist_SGN_HEAD2_NDX` (`sgn_head2`),
  KEY `famlist_SGN_HEAD3_NDX` (`sgn_head3`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `genlist` (
  `GENUS_ID` int(11) unsigned NOT NULL,
  `GENUS` VARCHAR(50) DEFAULT NULL,
  `AUTHORITY` VARCHAR(150) DEFAULT NULL,
  `DEFAULT_FAMILY_ID` int(11) DEFAULT NULL,
  `DEFAULT_FAMILY` VARCHAR(50) DEFAULT NULL,
  `GEN_LENGTH` int(2) DEFAULT NULL,
  `NEAR_MATCH_GENUS` VARCHAR(50) DEFAULT NULL,
  `SEARCH_GENUS_NAME` VARCHAR(50) DEFAULT NULL,
  `sgn_head1` char(1) DEFAULT NULL,
  `sgn_head2` char(2) DEFAULT NULL,
  `sgn_head3` char(3) DEFAULT NULL,
  `sgn_tail1` char(1) DEFAULT NULL,
  `sgn_tail2` char(2) DEFAULT NULL,
  `sgn_tail3` char(3) DEFAULT NULL,
  PRIMARY KEY  (`GENUS_ID`),
  UNIQUE KEY `GENUS_ID_2` (`GENUS_ID`),
  KEY `GENUS_ID` (`GENUS_ID`),
  KEY `DEFAULT_FAMILY_ID`(`DEFAULT_FAMILY_ID`),
  KEY `DEFAULT_FAMILY`(`DEFAULT_FAMILY`),
  KEY `GEN_LENGTH` (`GEN_LENGTH`),
  KEY `NEAR_MATCH_GENUS` (`NEAR_MATCH_GENUS`),
  KEY `SGN_HEAD1_NDX` (`sgn_head1`),
  KEY `SGN_HEAD2_NDX` (`sgn_head2`),
  KEY `SGN_HEAD3_NDX` (`sgn_head3`),
  KEY `SGN_TAIL1_NDX` (`sgn_tail1`),
  KEY `SGN_TAIL2_NDX` (`sgn_tail2`),
  KEY `SGN_TAIL3_NDX` (`sgn_tail3`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `splist` (
  `SPECIES_ID` int(11) NOT NULL,
  `GENUS_ORIG` VARCHAR(50) DEFAULT NULL,
  `SPECIES` VARCHAR(60) DEFAULT NULL,
  `GENUS_ID` int(11) DEFAULT NULL,
  `AUTHORITY` VARCHAR(150) DEFAULT NULL,
  `SP_LENGTH` int(2) DEFAULT NULL,
  `NEAR_MATCH_SPECIES` VARCHAR(60) DEFAULT NULL,
  `SEARCH_SPECIES_NAME` VARCHAR(60) DEFAULT NULL,
  PRIMARY KEY  (`SPECIES_ID`),
  KEY `splist_GENUS_ID_NDX` (`GENUS_ID`),
  KEY `splist_GENUS_ORIG_NDX`(`GENUS_ORIG`),
  KEY `splist_SPECIES_NDX`(`SPECIES`),
  KEY `splist_SP_LENGTH_NDX` (`SP_LENGTH`),
  KEY `splist_NEAR_MATCH_SPECIES_NDX` (`NEAR_MATCH_SPECIES`),
  KEY `splist_SPECIES_ID_NDX` (`SPECIES_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `infra1list` (
  `infra1_id` int(11) NOT NULL,
  `species_orig` VARCHAR(50) DEFAULT NULL,
  `infra1` VARCHAR(60) DEFAULT NULL,
  `infra1_norank` VARCHAR(60) DEFAULT NULL,
  `rank` VARCHAR(25) DEFAULT NULL,
  `species_id` int(11) DEFAULT NULL,
  `authority` VARCHAR(150) DEFAULT NULL,
  `infra1_length` int(2) DEFAULT NULL,
  `near_match_infra1` VARCHAR(60) DEFAULT NULL,
  `search_infra1_name` VARCHAR(60) DEFAULT NULL,
  PRIMARY KEY  (`infra1_id`),
  KEY `infra1list_species_id` (`species_id`),
  KEY `infra1list_species_orig`(`species_orig`),
  KEY `infra1list_infra1`(`infra1`),
  KEY `infra1list_infra1_length` (`infra1_length`),
  KEY `infra1list_near_match_infra1` (`near_match_infra1`),
  KEY `infra1list_infra1_id` (`infra1_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `infra2list` (
  `infra2_id` int(11) NOT NULL,
  `infra1_orig` VARCHAR(50) DEFAULT NULL,
  `infra2` VARCHAR(60) DEFAULT NULL,
  `infra2_norank` VARCHAR(60) DEFAULT NULL,
  `rank` VARCHAR(25) DEFAULT NULL,
  `infra1_id` int(11) DEFAULT NULL,
  `authority` VARCHAR(150) DEFAULT NULL,
  `infra2_length` int(2) DEFAULT NULL,
  `near_match_infra2` VARCHAR(60) DEFAULT NULL,
  `search_infra2_name` VARCHAR(60) DEFAULT NULL,
  PRIMARY KEY  (`infra2_id`),
  KEY `infra2list_infra1_id` (`infra1_id`),
  KEY `infra2list_infra1_orig`(`infra1_orig`),
  KEY `infra2list_infra2`(`infra2`),
  KEY `infra2list_infra2_length` (`infra2_length`),
  KEY `infra2list_near_match_infra2` (`near_match_infra2`),
  KEY `infra2list_infra2_id` (`infra2_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `genlist_famlist_combined` (
  `arbitrary_id` int(11) NOT NULL auto_increment,
  `genus_id` int(11) NOT NULL,
  `genus` VARCHAR(60) DEFAULT NULL,
  `search_genus_name` VARCHAR(60) DEFAULT NULL,
  `near_match_genus` VARCHAR(60) DEFAULT NULL,
  `near_match_fam_gen` VARCHAR(110) DEFAULT NULL,
  `family_genus` VARCHAR(110) DEFAULT NULL,
  `family_id` int(11) DEFAULT NULL,
  `gen_length` int(2) DEFAULT NULL,
  `near_match_family` VARCHAR(50) DEFAULT NULL,
  `search_family_name` VARCHAR(50) DEFAULT NULL,
  `fam_length` int(2) DEFAULT NULL,
  `family` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY  (`arbitrary_id`),
  KEY `FAMILY_ID_NDX` (`family_id`),
  KEY `NEAR_MATCH_GENUS_NDX` (`near_match_genus`),
  KEY `NEAR_MATCH_FAM_GEN_NDX` (`near_match_fam_gen`),
  KEY `GENUS_ID_NDX` (`genus_id`),
  KEY `GEN_LENGTH_NDX` (`gen_length`),
  KEY `FAM_LENGTH_NDX` (`fam_length`),
  KEY `NEAR_MATCH_FAMILY_NDX` (`near_match_family`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `splist_genlist_combined` (
  `arbitrary_id` int(11) NOT NULL auto_increment,
  `species_id` int(11) NOT NULL,
  `species` VARCHAR(60) DEFAULT NULL,
  `search_species_name` VARCHAR(60) DEFAULT NULL,
  `near_match_species` VARCHAR(60) DEFAULT NULL,
  `near_match_gen_sp` VARCHAR(110) DEFAULT NULL,
  `genus_species` VARCHAR(110) DEFAULT NULL,
  `genus_id` int(11) DEFAULT NULL,
  `sp_length` int(2) DEFAULT NULL,
  `near_match_genus` VARCHAR(50) DEFAULT NULL,
  `search_genus_name` VARCHAR(50) DEFAULT NULL,
  `gen_length` int(2) DEFAULT NULL,
  `genus` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY  (`arbitrary_id`),
  KEY `GENUS_ID_NDX` (`genus_id`),
  KEY `NEAR_MATCH_SPECIES_NDX` (`near_match_species`),
  KEY `NEAR_MATCH_GEN_SP_NDX` (`near_match_gen_sp`),
  KEY `SPECIES_ID_NDX` (`species_id`),
  KEY `SP_LENGTH_NDX` (`sp_length`),
  KEY `GEN_LENGTH_NDX` (`gen_length`),
  KEY `NEAR_MATCH_GENUS_NDX` (`near_match_genus`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `infra1list_splist_combined` (
  `arbitrary_id` int(11) NOT NULL auto_increment,
  `infra1_id` int(11) NOT NULL,
  `infra1` VARCHAR(60) DEFAULT NULL,
  `infra1_norank` VARCHAR(60) DEFAULT NULL,
  `rank` VARCHAR(25) DEFAULT NULL,
  `search_infra1_name` VARCHAR(60) DEFAULT NULL,
  `near_match_infra1` VARCHAR(60) DEFAULT NULL,
  `near_match_sp_infra1` VARCHAR(120) DEFAULT NULL,
  `species_infra1` VARCHAR(120) DEFAULT NULL,
  `species_infra1_norank` VARCHAR(120) DEFAULT NULL,
  `species_id` int(11) DEFAULT NULL,
  `infra1_length` int(2) DEFAULT NULL,
  `near_match_species` VARCHAR(50) DEFAULT NULL,
  `search_species_name` VARCHAR(50) DEFAULT NULL,
  `sp_length` int(2) DEFAULT NULL,
  `species` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY  (`arbitrary_id`),
  KEY `infra1list_splist_combined_species_id` (`species_id`),
  KEY `infra1list_splist_combined_rank` (`rank`),
  KEY `infra1list_splist_combined_species_infra1_norank` (`species_infra1_norank`),
  KEY `infra1list_splist_combined_species_infra1`(`species_infra1`),
  KEY `infra1list_splist_combined_near_match_infra1` (`near_match_infra1`),
  KEY `infra1list_splist_combined_near_match_sp_infra1` (`near_match_sp_infra1`),
  KEY `infra1list_splist_combined_infra1_id` (`infra1_id`),
  KEY `infra1list_splist_combined_infra1_length` (`infra1_length`),
  KEY `infra1list_splist_combined_sp_length` (`sp_length`),
  KEY `infra1list_splist_combined_near_match_species` (`near_match_species`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `infra2list_infra1list_combined` (
  `arbitrary_id` int(11) NOT NULL auto_increment,
  `infra2_id` int(11) NOT NULL,
  `infra2` VARCHAR(70) DEFAULT NULL,
  `rank2` VARCHAR(20) DEFAULT NULL,
  `infra2_norank` VARCHAR(60) DEFAULT NULL,
  `search_infra2_name` VARCHAR(60) DEFAULT NULL,
  `near_match_infra2` VARCHAR(60) DEFAULT NULL,
  `near_match_infra1_infra2` VARCHAR(110) DEFAULT NULL,
  `infra1_infra2` VARCHAR(120) DEFAULT NULL,
  `infra1_infra2_norank` VARCHAR(120) DEFAULT NULL,
  `infra1_id` int(11) DEFAULT NULL,
  `infra2_length` int(2) DEFAULT NULL,
  `near_match_infra1` VARCHAR(50) DEFAULT NULL,
  `search_infra1_name` VARCHAR(50) DEFAULT NULL,
  `infra1_length` int(2) DEFAULT NULL,
  `infra1` VARCHAR(70) DEFAULT NULL,
  `rank1` VARCHAR(20) DEFAULT NULL,
  `infra1_norank` VARCHAR(60) DEFAULT NULL,
  PRIMARY KEY  (`arbitrary_id`),
  KEY `infra2list_infra1list_combined_infra1_id` (`infra1_id`),
  KEY `infra2list_infra1list_combined_infra1_infra2_norank` (`infra1_infra2_norank`),
  KEY `infra2list_infra1list_combined_infra1_infra2`(`infra1_infra2`),
  KEY `infra2list_infra1list_combined_near_match_infra2` (`near_match_infra2`),
  KEY `infra2list_infra1list_combined_near_match_infra1_infra2` (`near_match_infra1_infra2`),
  KEY `infra2list_infra1list_combined_infra2_id` (`infra2_id`),
  KEY `infra2list_infra1list_combined_infra2_length` (`infra2_length`),
  KEY `infra2list_infra1list_combined_infra1_length` (`infra1_length`),
  KEY `infra2list_infra1list_combined_near_match_infra1` (`near_match_infra1`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
